### ISSUE TITLE
if display files on top, sort won't work

### ISSUE THREAD

**Issue by ugurtufekci** [ugurtufekci/AmazeFileManager#1]
Uygulama içinde farklı isimde filelar oluşturup bu fileları alfabetik olarak sort etmeye çalıştım. Bu sort işlemini sağ üstteki sort tabından directory sort mode' unu seçip daha sonra **files on top** modunda çalıştırdığımız zaman sort işlemi çalışmıyor. Yani default olan **folders on top** modunda çalışan sort işlemi **files on top** modunda çalışmıyor. Özetle filelar ile directorylerin beraber bulundugu bir alanda **files on top mod**unda sort işlemi çalışmıyor.Bu problemi yaptığım bir ön araştırma sonucunda daha çok FileListSorter.java dosyasında yapacağım değişikler ve buna bağlı olan bir kaç dosyadaki düzeltmeler ile gerçekleştirebileceğimi ön görüyorum.

**Comment by cagdasgerede** [comment]
Not enough description

**Comment by cagdasgerede** [comment]
Buradaki İngilizce tarifi anlayamıyorum. Ya İngilizceyi düzeltin, ya da Türkçe olarak yazın.

**Comment by cagdasgerede** [comment]
ok
