### ISSUE TITLE
Aynı dosya veya klasör isimlerinin tekrar tekrar oluşuyor olması 

### ISSUE THREAD

**Issue by aybikeaydemir** [ugurtufekci/AmazeFileManager#11]
File manager kopyalama veya taşıma işlemleri yapılabiliyor . Bir file baska bir directoriye tasıyabiliyor ya da kopyalanabiliyor. Secilmiş olan klasör  veya dosya hedef directory içerisinde daha önceden aynı isimli bir dosya veya klasör mevcutsa üzerine yaz veya dosya  / klasörün ismini değiştir uyarısını veriyor . Fakat her hangi bir directoriye siz yeni bir dosya oluşturmak /klasör oluşturmak veya dosyayı yeniden adlandır /klasörü yeniden adlandır seçeneğini seçip birden fazla dosya /klasörün isimlerinin
aynı yapabiliyorsunuz. txt , fotograf vs yani türünün de bir önemi olmaksızın bütün directoryinin adı aynı isimli dosyalardan veya klasörlerden böylelikle oluşabiliyor.

**Comment by cagdasgerede** [comment]
Anlattıgını tam anlamadım. Lütfen cümlelerini tekrar düzenle. Gerekirse screenshot koy.
