### ISSUE TITLE
root olarak gezinme 

### ISSUE THREAD

**Issue by aybikeaydemir** [ugurtufekci/AmazeFileManager#12]
Uygulamanın ayarlar kısmında root olarak gezinme ve izinleri göster seçenekleri bulunuyor.Root gezinmesi açılmadan tüm dosyalar üzerindeki izinleriniz gözüküyor . Root olarak gezinmeyi seçip dosya klasör izinlerini göster seceneğine tıkladığınızda ise değişen hiçbir şey olmuyor. Hala aynı klasör ve dosyalarda kullanıcının izinleri mevcut değil . Form sitesinde de bu sorun bizim uygulamamız ile ilgili gündeme getirilmiş.
https://forum.xda-developers.com/showpost.php?p=69829149&postcount=496

**Comment by cagdasgerede** [comment]
Tam olarak problem nedir anlayamadım. Tekrar açıklar mısın?
