### ISSUE TITLE
path bar error 

### ISSUE THREAD

**Issue by aybikeaydemir** [ugurtufekci/AmazeFileManager#13]
İçinde bulunan directoryden baska klasörlere geçildiğinde yukarda verilen path ile seçilen klasör veya dosyanın pathi birbirini tutmuyor. Directoryde bulanan baska bir dosya veya klasörün adresi gözüküyor.
Hatanın videosu : 
https://drive.google.com/file/d/0B0u8_WTGBLT8QUF6LTBxdUtTUkE/view

**Comment by cagdasgerede** [comment]
Bug nerede anlamadim? Videoda hangi adimda bug var açıklayınız.
