### ISSUE TITLE
More searching options

### ISSUE THREAD

**Issue by aybikeaydemir** [ugurtufekci/AmazeFileManager#14]
File managerda kopyalama veya taşıma işlemleri yapılabiliyor . Kopyalanan klasörde daha önceden aynı isimde dosya buluyorsa kopyalama işlemi yapılamıyor.Üzerine yaz ya da yeniden adlandır seçenekleri çıkıyor.Fakat taşıma veya kopyalama olmadan dosyayı yeniden adlandır seçeneğini seçtiğimizde aynı ismi birden fazla dosyaya  verebiliyoruz.Renamede , create file ve folderda yalnızca boşluk girilerek isimlendirilme yapılabiliyor .Create directory ve renamede dosyanın parenti ile aynı ismi almasına izin verilmiyor. .Bu problemleri düzelteceğim.Daha sonra etiketleme(label) özelliği ekleyeceğim . Böylelikle post / pre olarak belirlenen isimleri dosyalara varolan yeniden adlandır seçeneği ile eklenebilecek.Birden fazla dosyayı seçip işlem yapabiliyor olma özelliğini de ekleyeceğim. Yani seçili dosyaların hepsi aynı anda belirlenen post veya pre etiketi ile isimlendirilebilecek .Yapılan tüm etiketleme değişikleri Label History adı aldında tutulucak ve bu listeye menuden erişilebilecektir. Eğer etiketleme işlemi başarız sonuclanırsa (yanlış karekter kullanımı,dosyanın daha önceden var olması vs )bu listeye eklenmez. Etiketleme kaldırılırsa da bu listeden silinir.Searching toolda arama etiketlemeye göre yapılacak.Bu değişikler için müdahale edeceğim dosyalar : 
AmazeFileManager/src/main/java/com/amaze/filemanager/filesystem/...

**Comment by cagdasgerede** [comment]
Ok
