### ISSUE TITLE
Lock feature for folders and files.

### ISSUE THREAD

**Issue by ugurtufekci** [ugurtufekci/AmazeFileManager#3]
Adding new feature which is "Lock". Motivation is "everybody needs some privacy" for different situation. In this scenario we can provide this with Lock/Password. I will create new attribute named password then I will encrypt password against brute force or other attacks using with some encryption algorithms. I do not know which algorithm is optimal.  Nowadays I am focused on AES.

**Comment by cagdasgerede** [comment]
Not enough description.

**Comment by cagdasgerede** [comment]
ok

**Comment by cagdasgerede** [comment]
Ben " yeni dosya yaratamazsin " demedim.

**Comment by ugurtufekci** [comment]
Bu durumda her hangi bir sıkıntı yok yani değil mi hocam
Samsung Galaxy akıllı telefonumdan gönderildi.
-------- Orijinal mesaj --------Başlangıç tarihi: Cagdas Evren Gerede <notifications@github.com> Tarih: 11.03.2017  20:56  (GMT+03:00) Alıcı: ugurtufekci/AmazeFileManager <AmazeFileManager@noreply.github.com> Cc: ugurtufekci <ugurtufekci.tobbetu@gmail.com>, Assign <assign@noreply.github.com> Konu: Re: [ugurtufekci/AmazeFileManager] Lock feature for folders and files. (#3) 
Ben " yeni dosya yaratamazsin " demedim.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ugurtufekci/AmazeFileManager","title":"ugurtufekci/AmazeFileManager","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ugurtufekci/AmazeFileManager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cagdasgerede in #3: Ben \" yeni dosya yaratamazsin \" demedim."}],"action":{"name":"View Issue","url":"https://github.com/ugurtufekci/AmazeFileManager/issues/3#issuecomment-285886309"}}}

**Comment by cagdasgerede** [comment]
Yok
