### ISSUE TITLE
Network Manager:

### ISSUE THREAD

**Issue by aybikeaydemir** [ugurtufekci/AmazeFileManager#5]
In application, the IP address is taken but no connection is made with the PC. If this problem 'll solved, the files can be transferred from the phone to the computer via FTP Server. When the IP address is opened in the browser, all your files on the phone will be easily accessible from the PC. There is a sharing option with WiFi and Bluetooth, but there is not Bluetooth and WiFi direct sharing option for each file type, and I will add that too.

I'll change these packages or add some class : AmazeFileManager/src/main/java/com/amaze/filemanager/filesystem
AmazeFileManager/src/main/java/com/amaze/filemanager/services

**Comment by cagdasgerede** [comment]
Bu da uygulamanın dışında bir değişiklik. Bu haliyle uygun değil.

**Comment by aybikeaydemir** [comment]
zaten uygulamanın içinde bu issueları gerceklestiren classlar mevcut ama çalışmıyor .

**Comment by aybikeaydemir** [comment]
https://github.com/arpitkh96/AmazeFileManager/issues/403
https://github.com/arpitkh96/AmazeFileManager/issues/404

yanlış mı yorumluyorum ?

**Comment by cagdasgerede** [comment]
Problemi ve ne yapacağını tekrar anlatır mısın?
