### ISSUE TITLE
Document Editor: 

### ISSUE THREAD

**Issue by aybikeaydemir** [ugurtufekci/AmazeFileManager#6]
In application, you can create files with .txt extensions or view contents of txt files. But the contents of these files can not be added or changed. I will fix the ability to change the contents of your .txt files. So you can easily edit files when the phone is rooted. The editor will support all kinds of text files such as HTML, XHTML, and TEXT.

I 'll change this class : src/main/java/com/amaze/filemanager/activities/  TextReader.java or I'll add new class.

**Comment by cagdasgerede** [comment]
Bu söylediğin uygulamanın dışında bir değişiklik. Bu haliyle uygun değil.
