### ISSUE TITLE
Short Cut : 

### ISSUE THREAD

**Issue by aybikeaydemir** [ugurtufekci/AmazeFileManager#7]
I will add shortcuts to the home screen to make it easier to access folders (videos, photos etc). This will make it easier to access the video or picture without entering the phone gallery.

I'll add new classes because our application has not this feature .

**Comment by cagdasgerede** [comment]
Böyle yüzeysel arayüz değişikliklerinin uygun olmadığını söylemiştim. Bu haliyle uygun değil.
